### ISSUE TITLE
Не коректно відображаються інтерактивні приклади з кодом.

### ISSUE THREAD

**Issue by orknarok** [webdoky/platform#74]
Наприклад: https://webdoky.org/uk/docs/Web/JavaScript/Reference/Global_Objects/String/Trim/

![Capture047-20220623](https://user-images.githubusercontent.com/32248521/175300169-afca7afd-8ecb-44f2-96ae-0f5f75267797.png)

**Comment by AdriandeCita** [comment]
Дякую! Виправлено в рамках міграції на нову платформу, check it out https://webdoky.org/uk/docs/Web/JavaScript/Reference/Global_Objects/String/Trim/

Конкретно тут https://github.com/webdoky/platform-next/commit/831e5636075e0dd97af2ee7c2df85f6e58c337c2
